full_rebuild: true
name: SecConVids
description: The security conference video hub
#destination: jekyllbuild
url: #place url
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: false #change to false if you want to use pagination
plugins: 
    - jekyll-paginate

tag_dir: /tag
category_dir: /category

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page-classic-sidebar-left"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, _site]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post-full"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "YouTube"
              value: "youtube"
            - name: "CCC"
              value: "ccc"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"
